# Generated by Django 4.2.28 on 2026-02-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(default='whatsapp', help_text='Channel source for this contact (e.g., whatsapp)', max_length=50),
        ),
    ]
