# Generated by Django 4.2.28 on 2026-02-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this flow (used as an identifier).', max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='A user-friendly name for display purposes.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this flow does.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is this flow currently active and can be triggered?')),
                ('trigger_keywords', models.JSONField(blank=True, default=list, help_text='List of keywords/phrases that can trigger this flow (e.g., ["solar panel", "quote", "installation"]). Case-insensitive match.')),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Configuration for advanced triggers, e.g., regex for data extraction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversational Flow',
                'verbose_name_plural': 'Conversational Flows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Session-specific data collected during the flow (e.g., user responses, calculated values).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flow Session',
                'verbose_name_plural': 'Flow Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this step (e.g., 'Welcome Message', 'Ask System Size').", max_length=255)),
                ('step_type', models.CharField(choices=[('send_message', 'Send Message'), ('question', 'Ask Question'), ('condition', 'Conditional Branch'), ('action', 'Perform Action'), ('wait_for_reply', 'Wait for Reply'), ('end_flow', 'End Flow'), ('start_flow_node', 'Start Flow Node'), ('human_handover', 'Handover to Human Agent'), ('switch_flow', 'Switch to Another Flow')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for this step, structure depends on step_type.')),
                ('is_entry_point', models.BooleanField(default=False, help_text='Is this the first step of the flow? Only one step per flow should be an entry point.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flow Step',
                'verbose_name_plural': 'Flow Steps',
                'ordering': ['flow', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the condition that triggers this transition.')),
                ('priority', models.IntegerField(default=0, help_text='Order of evaluation for transitions from the same step (lower numbers evaluated first).')),
            ],
            options={
                'verbose_name': 'Flow Transition',
                'verbose_name_plural': 'Flow Transitions',
                'ordering': ['current_step', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this WhatsApp flow (used as an identifier).', max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='A user-friendly name for display purposes.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this flow does.', null=True)),
                ('flow_id', models.CharField(blank=True, db_index=True, help_text='The flow ID returned by Meta after syncing.', max_length=100, null=True, unique=True)),
                ('flow_json', models.JSONField(help_text="The WhatsApp Flow JSON definition conforming to Meta's Flow JSON schema.")),
                ('sync_status', models.CharField(choices=[('draft', 'Draft'), ('syncing', 'Syncing with Meta'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('error', 'Sync Error')], db_index=True, default='draft', help_text='Current sync status with Meta.', max_length=20)),
                ('sync_error', models.TextField(blank=True, help_text='Error message if sync failed.', null=True)),
                ('version', models.IntegerField(default=1, help_text='Version number of this flow definition.')),
                ('is_active', models.BooleanField(default=False, help_text='Is this flow currently active and can be triggered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with Meta.', null=True)),
                ('flow_definition', models.ForeignKey(blank=True, help_text='Optional link to the traditional flow definition this replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flows', to='flows.flow')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow',
                'verbose_name_plural': 'WhatsApp Flows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppFlowResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_token', models.CharField(help_text='The flow token from Meta that identifies this flow session.', max_length=255)),
                ('response_data', models.JSONField(help_text='The complete response payload from the user, including all form data.')),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Whether this response has been processed by the system.')),
                ('processing_notes', models.TextField(blank=True, help_text='Notes or results from processing this response.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when this response was processed.', null=True)),
                ('contact', models.ForeignKey(help_text='The contact who submitted this flow response.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flow_responses', to='conversations.contact')),
                ('whatsapp_flow', models.ForeignKey(help_text='The WhatsApp flow this response is for.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='flows.whatsappflow')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow Response',
                'verbose_name_plural': 'WhatsApp Flow Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
