# Generated by Django 4.2.28 on 2026-02-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_integration', '0001_initial'),
        ('flows', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappflow',
            name='meta_app_config',
            field=models.ForeignKey(help_text='The Meta app configuration this flow is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flows', to='meta_integration.metaappconfig'),
        ),
        migrations.AddField(
            model_name='flowtransition',
            name='current_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='flows.flowstep'),
        ),
        migrations.AddField(
            model_name='flowtransition',
            name='next_step',
            field=models.ForeignKey(help_text='The step to transition to if conditions are met.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='flows.flowstep'),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowsession',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='conversations.contact'),
        ),
        migrations.AddField(
            model_name='flowsession',
            name='current_step',
            field=models.ForeignKey(blank=True, help_text='The current step the user is at in this flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.flowstep'),
        ),
        migrations.AddField(
            model_name='flowsession',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow'),
        ),
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together={('flow', 'name')},
        ),
    ]
